import type { Exercise, Location, TemplateSlot, WorkoutTemplate } from "./types";

const both: Location[] = ["office", "home"];

export const exercises: Exercise[] = [
  {
    id: "double-dumbbell-front-squat",
    name: "Double-dumbbell front squat",
    category: "squat",
    locations: both,
    equipment: ["Two dumbbells"],
    loadMode: "dumbbell_pair",
    instructions: "Hold both dumbbells at shoulder height. Brace, sit between your hips, and drive through your whole foot.",
    demonstrationUrl: null,
  },
  {
    id: "dumbbell-goblet-squat",
    name: "Dumbbell goblet squat",
    category: "squat",
    locations: both,
    equipment: ["One dumbbell"],
    loadMode: "dumbbell_single",
    instructions: "Hold one dumbbell at your chest. Keep your ribs stacked and knees tracking over your toes.",
    demonstrationUrl: null,
  },
  {
    id: "heel-elevated-dumbbell-squat",
    name: "Heel-elevated dumbbell squat",
    category: "squat",
    locations: ["office"],
    equipment: ["Two dumbbells", "Small heel wedge or plates"],
    loadMode: "dumbbell_pair",
    instructions: "Elevate both heels, stay tall, and let the knees travel forward while keeping the whole forefoot planted.",
    demonstrationUrl: null,
  },
  {
    id: "dumbbell-bulgarian-split-squat",
    name: "Dumbbell Bulgarian split squat",
    category: "squat",
    locations: ["office"],
    equipment: ["Two dumbbells", "Adjustable bench"],
    loadMode: "dumbbell_pair",
    instructions: "Rest the rear foot on the bench. Lower the back knee under control and drive through the front foot.",
    demonstrationUrl: null,
  },
  {
    id: "dumbbell-split-squat",
    name: "Dumbbell split squat with both feet on the floor",
    category: "squat",
    locations: both,
    equipment: ["Two dumbbells"],
    loadMode: "dumbbell_pair",
    instructions: "Use a stable staggered stance. Drop the rear knee down and keep most pressure through the front foot.",
    demonstrationUrl: null,
  },
  {
    id: "cable-front-squat",
    name: "Cable front squat",
    category: "squat",
    locations: ["office"],
    equipment: ["Low cable station", "Rope or straight-bar attachment"],
    loadMode: "cable_stack",
    instructions: "Hold the cable at chest height, step back for tension, brace, and squat without letting the stack pull you forward.",
    demonstrationUrl: null,
  },
  {
    id: "heel-elevated-goblet-squat",
    name: "Heel-elevated goblet squat",
    category: "squat",
    locations: ["home"],
    equipment: ["One dumbbell", "Small heel wedge or plates"],
    loadMode: "dumbbell_single",
    instructions: "Hold the dumbbell at your chest, keep your torso tall, and lower with both heels supported.",
    demonstrationUrl: null,
  },
  {
    id: "band-resisted-squat",
    name: "Band-resisted squat",
    category: "squat",
    locations: ["home"],
    equipment: ["Resistance band"],
    loadMode: "band",
    instructions: "Stand evenly on the band with it secured at shoulder height. Brace and keep tension through the full squat.",
    demonstrationUrl: null,
  },

  {
    id: "kneeling-cable-lat-pulldown",
    name: "Kneeling cable lat pulldown",
    category: "pull",
    subtype: "vertical",
    locations: ["office"],
    equipment: ["High cable station", "Pulldown attachment"],
    loadMode: "cable_stack",
    instructions: "Kneel tall, set your ribs down, and pull your elbows toward your sides without leaning back.",
    demonstrationUrl: null,
  },
  {
    id: "half-kneeling-single-arm-cable-pulldown",
    name: "Half-kneeling single-arm cable pulldown",
    category: "pull",
    subtype: "vertical",
    locations: ["office"],
    equipment: ["High cable station", "Single handle"],
    loadMode: "cable_stack",
    instructions: "Kneel with the working-side knee down. Pull the elbow toward your hip while keeping your torso still.",
    demonstrationUrl: null,
  },
  {
    id: "straight-arm-cable-pulldown",
    name: "Straight-arm cable pulldown",
    category: "pull",
    subtype: "vertical",
    locations: ["office"],
    equipment: ["High cable station", "Rope or straight-bar attachment"],
    loadMode: "cable_stack",
    instructions: "Keep a soft elbow bend and pull the handle from shoulder height to your thighs without rocking.",
    demonstrationUrl: null,
  },
  {
    id: "chest-supported-dumbbell-row",
    name: "Chest-supported dumbbell row",
    category: "pull",
    subtype: "horizontal",
    locations: ["office"],
    equipment: ["Two dumbbells", "Incline bench"],
    loadMode: "dumbbell_pair",
    instructions: "Keep your chest on the bench and row both elbows back. Pause without shrugging.",
    demonstrationUrl: null,
  },
  {
    id: "seated-low-cable-row",
    name: "Seated low-cable row",
    category: "pull",
    subtype: "horizontal",
    locations: ["office"],
    equipment: ["Low cable station", "Row handle"],
    loadMode: "cable_stack",
    instructions: "Sit tall, brace your feet, and pull the handle to your lower ribs without swinging.",
    demonstrationUrl: null,
  },
  {
    id: "one-arm-dumbbell-row",
    name: "One-arm dumbbell row",
    category: "pull",
    subtype: "horizontal",
    locations: ["office"],
    equipment: ["One dumbbell", "Bench"],
    loadMode: "dumbbell_single",
    instructions: "Brace on the bench, keep your spine long, and row the dumbbell toward your hip.",
    demonstrationUrl: null,
  },
  {
    id: "standing-single-arm-cable-row",
    name: "Standing single-arm cable row",
    category: "pull",
    subtype: "horizontal",
    locations: ["office"],
    equipment: ["Middle cable station", "Single handle"],
    loadMode: "cable_stack",
    instructions: "Stand square and braced. Row to your ribs without twisting your torso.",
    demonstrationUrl: null,
  },
  {
    id: "kneeling-two-arm-band-lat-pulldown",
    name: "Kneeling two-arm band lat pulldown",
    category: "pull",
    subtype: "vertical",
    locations: ["home"],
    equipment: ["Resistance band", "High door anchor"],
    loadMode: "band",
    instructions: "Kneel beneath the high anchor and pull both elbows down toward your sides while staying tall.",
    demonstrationUrl: null,
  },
  {
    id: "half-kneeling-single-arm-band-lat-pulldown",
    name: "Half-kneeling single-arm band lat pulldown",
    category: "pull",
    subtype: "vertical",
    locations: ["home"],
    equipment: ["Resistance band", "High door anchor"],
    loadMode: "band",
    instructions: "Keep your ribs down and pull one elbow toward your hip without leaning or rotating.",
    demonstrationUrl: null,
  },
  {
    id: "straight-arm-band-pulldown",
    name: "Straight-arm band pulldown",
    category: "pull",
    subtype: "vertical",
    locations: ["home"],
    equipment: ["Resistance band", "High door anchor"],
    loadMode: "band",
    instructions: "With a soft elbow bend, sweep the band from shoulder height to your thighs without arching your back.",
    demonstrationUrl: null,
  },
  {
    id: "one-arm-dumbbell-row-thigh-braced",
    name: "One-arm dumbbell row braced against the thigh",
    category: "pull",
    subtype: "horizontal",
    locations: ["home"],
    equipment: ["One dumbbell"],
    loadMode: "dumbbell_single",
    instructions: "Hinge and brace the free hand on your thigh. Row toward your hip without rotating.",
    demonstrationUrl: null,
  },
  {
    id: "two-dumbbell-bent-over-row",
    name: "Two-dumbbell bent-over row",
    category: "pull",
    subtype: "horizontal",
    locations: ["home"],
    equipment: ["Two dumbbells"],
    loadMode: "dumbbell_pair",
    instructions: "Hinge with a flat back and row both dumbbells toward your hips. Keep your torso fixed.",
    demonstrationUrl: null,
  },
  {
    id: "seated-resistance-band-row",
    name: "Seated resistance-band row",
    category: "pull",
    subtype: "horizontal",
    locations: ["home"],
    equipment: ["Resistance band", "Low door anchor"],
    loadMode: "band",
    instructions: "Sit tall facing the low anchor and pull toward your ribs. Avoid leaning back to finish the rep.",
    demonstrationUrl: null,
  },

  {
    id: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian deadlift",
    category: "hamstring",
    subtype: "hinge",
    locations: both,
    equipment: ["Two dumbbells"],
    loadMode: "dumbbell_pair",
    instructions: "Push your hips back with soft knees and keep the dumbbells close. Stop when your hamstrings limit the hinge.",
    demonstrationUrl: null,
  },
  {
    id: "b-stance-dumbbell-romanian-deadlift",
    name: "B-stance dumbbell Romanian deadlift",
    category: "hamstring",
    subtype: "hinge",
    locations: both,
    equipment: ["Two dumbbells"],
    loadMode: "dumbbell_pair",
    instructions: "Place the support foot slightly behind. Load the front leg and hinge your hips straight back.",
    demonstrationUrl: null,
  },
  {
    id: "single-leg-dumbbell-romanian-deadlift",
    name: "Single-leg dumbbell Romanian deadlift",
    category: "hamstring",
    subtype: "hinge",
    locations: both,
    equipment: ["Two dumbbells"],
    loadMode: "dumbbell_pair",
    instructions: "Keep your hips square as the free leg reaches back. Hinge over the planted leg with control.",
    demonstrationUrl: null,
  },
  {
    id: "cable-pull-through",
    name: "Cable pull-through",
    category: "hamstring",
    subtype: "hinge",
    locations: ["office"],
    equipment: ["Low cable station", "Rope attachment"],
    loadMode: "cable_stack",
    instructions: "Face away from the stack, hinge back, then squeeze your glutes to stand without leaning backward.",
    demonstrationUrl: null,
  },
  {
    id: "standing-single-leg-cable-hamstring-curl",
    name: "Standing single-leg cable hamstring curl",
    category: "hamstring",
    subtype: "curl",
    locations: ["office"],
    equipment: ["Low cable station", "Cable ankle cuff"],
    loadMode: "cable_stack",
    instructions: "Keep both thighs aligned and curl your heel toward your glute without arching your back.",
    demonstrationUrl: null,
  },
  {
    id: "prone-cable-hamstring-curl-bench",
    name: "Prone cable hamstring curl on the bench",
    category: "hamstring",
    subtype: "curl",
    locations: ["office"],
    equipment: ["Low cable station", "Cable ankle cuff", "Bench"],
    loadMode: "cable_stack",
    instructions: "Lie face down with hips heavy on the bench. Curl your heel in without lifting the thigh.",
    demonstrationUrl: null,
  },
  {
    id: "seated-cable-hamstring-curl-bench",
    name: "Seated cable hamstring curl on the bench",
    category: "hamstring",
    subtype: "curl",
    locations: ["office"],
    equipment: ["Low cable station", "Cable ankle cuff", "Bench"],
    loadMode: "cable_stack",
    instructions: "Sit tall with the cuff attached and curl your heel beneath the bench while keeping the thigh still.",
    demonstrationUrl: null,
  },
  {
    id: "prone-dumbbell-hamstring-curl-bench",
    name: "Prone dumbbell hamstring curl on the bench",
    category: "hamstring",
    subtype: "curl",
    locations: ["office"],
    equipment: ["One dumbbell", "Bench"],
    loadMode: "dumbbell_single",
    instructions: "Secure a light dumbbell between your feet and curl slowly. Keep your hips pressed into the bench.",
    demonstrationUrl: null,
  },
  {
    id: "resistance-band-good-morning",
    name: "Resistance-band good morning",
    category: "hamstring",
    subtype: "hinge",
    locations: ["home"],
    equipment: ["Resistance band"],
    loadMode: "band",
    instructions: "Stand on the band with it across your shoulders. Push your hips back, then stand tall under control.",
    demonstrationUrl: null,
  },
  {
    id: "prone-band-hamstring-curl-floor",
    name: "Prone band hamstring curl on the floor",
    category: "hamstring",
    subtype: "curl",
    locations: ["home"],
    equipment: ["Resistance band", "Low door anchor"],
    loadMode: "band",
    instructions: "Lie face down and curl both heels toward your glutes. Keep your hips and thighs down.",
    demonstrationUrl: null,
  },
  {
    id: "standing-single-leg-band-hamstring-curl",
    name: "Standing single-leg band hamstring curl",
    category: "hamstring",
    subtype: "curl",
    locations: ["home"],
    equipment: ["Resistance band", "Low door anchor"],
    loadMode: "band",
    instructions: "Face the anchor and curl one heel back while keeping your knees aligned and torso still.",
    demonstrationUrl: null,
  },
  {
    id: "seated-single-leg-band-hamstring-curl-floor",
    name: "Seated single-leg band hamstring curl from the floor",
    category: "hamstring",
    subtype: "curl",
    locations: ["home"],
    equipment: ["Resistance band", "Low door anchor"],
    loadMode: "band",
    instructions: "Sit facing the low anchor and pull one heel toward you while keeping the thigh still.",
    demonstrationUrl: null,
  },
  {
    id: "sliding-hamstring-curl",
    name: "Sliding hamstring curl",
    category: "hamstring",
    subtype: "curl",
    locations: ["home"],
    equipment: ["Furniture sliders or towels", "Smooth floor"],
    loadMode: "bodyweight",
    instructions: "Bridge your hips up, slide your heels away slowly, then curl them back without dropping your hips.",
    demonstrationUrl: null,
  },

  {
    id: "barbell-bench-press",
    name: "Barbell bench press",
    category: "push",
    subtype: "horizontal",
    locations: ["office"],
    equipment: ["Barbell", "Bench", "Rack"],
    loadMode: "barbell_total",
    instructions: "Set your shoulder blades, lower the bar to your lower chest, and press while keeping your feet planted.",
    demonstrationUrl: null,
  },
  {
    id: "flat-dumbbell-bench-press",
    name: "Flat dumbbell bench press",
    category: "push",
    subtype: "horizontal",
    locations: ["office"],
    equipment: ["Two dumbbells", "Flat bench"],
    loadMode: "dumbbell_pair",
    instructions: "Keep your shoulder blades set and press both dumbbells up over your chest without bouncing.",
    demonstrationUrl: null,
  },
  {
    id: "incline-dumbbell-bench-press",
    name: "Incline dumbbell bench press",
    category: "push",
    subtype: "horizontal",
    locations: ["office"],
    equipment: ["Two dumbbells", "Incline bench"],
    loadMode: "dumbbell_pair",
    instructions: "Use a moderate incline, keep your shoulder blades set, and press without shrugging.",
    demonstrationUrl: null,
  },
  {
    id: "dumbbell-floor-press",
    name: "Dumbbell floor press",
    category: "push",
    subtype: "horizontal",
    locations: both,
    equipment: ["Two dumbbells", "Floor"],
    loadMode: "dumbbell_pair",
    instructions: "Lie on the floor, pause your upper arms gently on the ground, and press the dumbbells over your chest.",
    demonstrationUrl: null,
  },
  {
    id: "standing-single-arm-cable-chest-press",
    name: "Standing single-arm cable chest press",
    category: "push",
    subtype: "horizontal",
    locations: ["office"],
    equipment: ["Middle cable station", "Single handle"],
    loadMode: "cable_stack",
    instructions: "Stand staggered and braced. Press forward without allowing your torso to rotate.",
    demonstrationUrl: null,
  },
  {
    id: "seated-dumbbell-shoulder-press",
    name: "Seated dumbbell shoulder press",
    category: "push",
    subtype: "vertical",
    locations: ["office"],
    equipment: ["Two dumbbells", "Adjustable bench"],
    loadMode: "dumbbell_pair",
    instructions: "Sit tall with back support and press overhead without flaring your ribs or shrugging.",
    demonstrationUrl: null,
  },
  {
    id: "standing-dumbbell-overhead-press",
    name: "Standing dumbbell overhead press",
    category: "push",
    subtype: "vertical",
    locations: both,
    equipment: ["Two dumbbells"],
    loadMode: "dumbbell_pair",
    instructions: "Brace your trunk and press both dumbbells overhead without leaning back.",
    demonstrationUrl: null,
  },
  {
    id: "half-kneeling-single-arm-cable-overhead-press",
    name: "Half-kneeling single-arm cable overhead press",
    category: "push",
    subtype: "vertical",
    locations: ["office"],
    equipment: ["Low cable station", "Single handle"],
    loadMode: "cable_stack",
    instructions: "Kneel with the working-side knee down and press overhead while keeping your ribs stacked.",
    demonstrationUrl: null,
  },
  {
    id: "single-arm-dumbbell-floor-press",
    name: "Single-arm dumbbell floor press",
    category: "push",
    subtype: "horizontal",
    locations: ["home"],
    equipment: ["One dumbbell", "Floor"],
    loadMode: "dumbbell_single",
    instructions: "Press one dumbbell from the floor while bracing hard enough to keep your torso square.",
    demonstrationUrl: null,
  },
  {
    id: "push-up",
    name: "Push-up",
    category: "push",
    subtype: "horizontal",
    locations: ["home"],
    equipment: ["Floor"],
    loadMode: "bodyweight",
    instructions: "Keep a straight line from shoulders to heels and lower your chest between your hands with control.",
    demonstrationUrl: null,
  },
  {
    id: "standing-band-chest-press",
    name: "Standing band chest press",
    category: "push",
    subtype: "horizontal",
    locations: ["home"],
    equipment: ["Resistance band", "Middle door anchor"],
    loadMode: "band",
    instructions: "Face away from the anchor, brace in a staggered stance, and press forward without leaning.",
    demonstrationUrl: null,
  },
  {
    id: "half-kneeling-single-arm-dumbbell-overhead-press",
    name: "Half-kneeling single-arm dumbbell overhead press",
    category: "push",
    subtype: "vertical",
    locations: ["home"],
    equipment: ["One dumbbell"],
    loadMode: "dumbbell_single",
    instructions: "Kneel with the working-side knee down and press overhead while keeping your torso tall.",
    demonstrationUrl: null,
  },
  {
    id: "standing-band-overhead-press",
    name: "Standing band overhead press",
    category: "push",
    subtype: "vertical",
    locations: ["home"],
    equipment: ["Resistance band"],
    loadMode: "band",
    instructions: "Stand evenly on the band, brace, and press overhead without leaning back.",
    demonstrationUrl: null,
  },
];

const slot = (
  id: string,
  position: 1 | 2 | 3 | 4,
  superset: "A" | "B",
  scheduledExerciseId: string,
  repMin: number,
  repMax: number,
  perSide = false,
): TemplateSlot => ({
  id,
  position,
  superset,
  scheduledExerciseId,
  sets: 3,
  repMin,
  repMax,
  perSide,
});

export const templates: WorkoutTemplate[] = [
  {
    id: "office-day-1",
    location: "office",
    day: 1,
    firstSuperset: "A",
    slots: [
      slot("office-day-1-slot-1", 1, "A", "double-dumbbell-front-squat", 6, 8),
      slot("office-day-1-slot-2", 2, "A", "kneeling-cable-lat-pulldown", 8, 10),
      slot("office-day-1-slot-3", 3, "B", "standing-single-leg-cable-hamstring-curl", 10, 12, true),
      slot("office-day-1-slot-4", 4, "B", "barbell-bench-press", 10, 12),
    ],
  },
  {
    id: "office-day-2",
    location: "office",
    day: 2,
    firstSuperset: "B",
    slots: [
      slot("office-day-2-slot-1", 1, "B", "dumbbell-romanian-deadlift", 6, 8),
      slot("office-day-2-slot-2", 2, "B", "seated-dumbbell-shoulder-press", 8, 10),
      slot("office-day-2-slot-3", 3, "A", "dumbbell-bulgarian-split-squat", 10, 12, true),
      slot("office-day-2-slot-4", 4, "A", "chest-supported-dumbbell-row", 10, 12),
    ],
  },
  {
    id: "office-day-3",
    location: "office",
    day: 3,
    firstSuperset: "A",
    slots: [
      slot("office-day-3-slot-1", 1, "A", "heel-elevated-dumbbell-squat", 6, 8),
      slot("office-day-3-slot-2", 2, "A", "straight-arm-cable-pulldown", 8, 10),
      slot("office-day-3-slot-3", 3, "B", "single-leg-dumbbell-romanian-deadlift", 10, 12, true),
      slot("office-day-3-slot-4", 4, "B", "incline-dumbbell-bench-press", 10, 12),
    ],
  },
  {
    id: "home-day-1",
    location: "home",
    day: 1,
    firstSuperset: "A",
    slots: [
      slot("home-day-1-slot-1", 1, "A", "dumbbell-goblet-squat", 6, 8),
      slot("home-day-1-slot-2", 2, "A", "kneeling-two-arm-band-lat-pulldown", 8, 10),
      slot("home-day-1-slot-3", 3, "B", "prone-band-hamstring-curl-floor", 10, 12),
      slot("home-day-1-slot-4", 4, "B", "dumbbell-floor-press", 10, 12),
    ],
  },
  {
    id: "home-day-2",
    location: "home",
    day: 2,
    firstSuperset: "B",
    slots: [
      slot("home-day-2-slot-1", 1, "B", "b-stance-dumbbell-romanian-deadlift", 6, 8),
      slot("home-day-2-slot-2", 2, "B", "standing-dumbbell-overhead-press", 8, 10),
      slot("home-day-2-slot-3", 3, "A", "band-resisted-squat", 10, 12),
      slot("home-day-2-slot-4", 4, "A", "one-arm-dumbbell-row-thigh-braced", 10, 12, true),
    ],
  },
  {
    id: "home-day-3",
    location: "home",
    day: 3,
    firstSuperset: "A",
    slots: [
      slot("home-day-3-slot-1", 1, "A", "dumbbell-split-squat", 6, 8, true),
      slot("home-day-3-slot-2", 2, "A", "straight-arm-band-pulldown", 8, 10),
      slot("home-day-3-slot-3", 3, "B", "seated-single-leg-band-hamstring-curl-floor", 10, 12, true),
      slot("home-day-3-slot-4", 4, "B", "standing-band-chest-press", 10, 12),
    ],
  },
];

export const exerciseById = new Map(exercises.map((exercise) => [exercise.id, exercise]));

export function getTemplate(location: Location, day: 1 | 2 | 3) {
  const template = templates.find((item) => item.location === location && item.day === day);
  if (!template) throw new Error(`Missing template for ${location} day ${day}`);
  return template;
}

export const categoryLabels = {
  squat: "Squat",
  pull: "Pull",
  hamstring: "Hamstring",
  push: "Push",
} as const;

export const subtypeLabels = {
  horizontal: "Horizontal",
  vertical: "Vertical",
  hinge: "Hinge",
  curl: "Curl",
} as const;
